[server]
address = ":8080"
api_prefix = "/api/insights-results-aggregator/v1/"
api_spec_file = "openapi.json"

[content]
path = "content.json"

[groups]
path = "groups_config.yaml"

[paths]
mock_data = "data"

