name: BDD tests

on:
  - push
  - pull_request

jobs:
  bdd:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:
          - "1.20"
    name: BDD for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: make build
