name: Go linters

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:
          - "1.20"
          - "1.21"
    name: Go ${{ matrix.go-version}}
    steps:
      - name: Unit tests
        run: env
        run: go test -coverprofile coverage.out $(go list ./... | grep -v tests)
        run: go tool cover -func=coverage.out
        run: bash <(curl -s https://codecov.io/bash)
      - name: REST API tests
        run: ./run_on_ci.sh
        run: ./test.sh
